import {QUESTIONS,ISSUES} from "../dist/config.js";
import {calculate} from "../dist/scoring.js";

const RANDOM_INITIALIZATIONS=120000,RESTARTS=180,TOP_SEEDS=60,MAX_PASSES=20;
const randomAnswers=()=>QUESTIONS.map(()=>Math.floor(Math.random()*4));
const cache=new Map();
const evaluate=a=>{const key=a.join("");let r=cache.get(key);if(!r){r=calculate(a);cache.set(key,r)}return r;};
const deficits=(r,target)=>{const n=r.normalized,i=r.issues,vals=Object.values(i).sort((a,b)=>b-a);if(target===10)return{displayRescue:Math.max(0,72-r.displayRescue),T:Math.max(0,55-n.T),P:Math.max(0,52-n.P),H:Math.max(0,50-n.H),R:Math.max(0,52-n.R)};if(target===11)return{displayRescue:Math.max(0,78-r.displayRescue),H:Math.max(0,58-n.H),R:Math.max(0,58-n.R),D:Math.max(0,58-r.D),thirdIssue:Math.max(0,55-vals[2])};return{displayRescue:Math.max(0,88-r.displayRescue),S:Math.max(0,55-n.S),P:Math.max(0,55-n.P),T:Math.max(0,55-n.T),H:Math.max(0,55-n.H),R:Math.max(0,55-n.R),people:Math.max(0,45-i.people),succession:Math.max(0,45-i.succession),court:Math.max(0,45-i.court),military:Math.max(0,45-i.military),local:Math.max(0,45-i.local),K:Math.max(0,50-r.K)};};
const objective=(r,target)=>{if(target==="max")return r.rawRescue;if(r.ending.number===target)return 1e6+r.rawRescue;const d=Object.values(deficits(r,target)).reduce((a,b)=>a+b,0);return-d+(r.displayRescue*.001);};
function hill(seed,target){let a=[...seed],r=evaluate(a),score=objective(r,target);for(let pass=0;pass<MAX_PASSES;pass++){let bestScore=score,best=null,bestR=null;for(let q=0;q<24;q++){const old=a[q];for(let x=0;x<4;x++){if(x===old)continue;const next=[...a];next[q]=x;const nr=evaluate(next),ns=objective(nr,target);if(ns>bestScore){bestScore=ns;best=next;bestR=nr}}}if(!best)break;a=best;r=bestR;score=bestScore;}return{answers:a,result:r,score};}
function search(target){const top=[];for(let i=0;i<RANDOM_INITIALIZATIONS;i++){const answers=randomAnswers(),result=evaluate(answers),score=objective(result,target);if(top.length<TOP_SEEDS||score>top.at(-1).score){top.push({answers,result,score});top.sort((a,b)=>b.score-a.score);top.length=Math.min(TOP_SEEDS,top.length)}}let best=top[0];const seeds=[...top.map(x=>x.answers),...Array.from({length:RESTARTS-TOP_SEEDS},randomAnswers)];for(const seed of seeds){const found=hill(seed,target);if(found.score>best.score)best=found;if(target!=="max"&&best.result.ending.number===target)break;}return best;}
const compact=x=>({answers:x.answers.map(n=>"ABCD"[n]).join(""),rawRescue:+x.result.rawRescue.toFixed(4),displayRescue:x.result.displayRescue,dimensions:x.result.normalized,issues:x.result.issues,D:+x.result.D.toFixed(3),K:x.result.K,ending:`${x.result.ending.number} ${x.result.ending.name}`});
const best=search("max"),targets={};for(const target of [10,11,12]){const x=search(target);targets[target]={found:x.result.ending.number===target,...compact(x),targetDeficits:deficits(x.result,target),distanceTo11:deficits(x.result,11),distanceTo12:deficits(x.result,12)};}
console.log(JSON.stringify({method:{randomInitializationsPerGoal:RANDOM_INITIALIZATIONS,restartsPerGoal:RESTARTS,topSeeds:TOP_SEEDS,maxHillPasses:MAX_PASSES,cachedEvaluations:cache.size},globalBest:compact(best),targets},null,2));
