import {QUESTIONS,DIMENSIONS,ISSUES} from "../dist/config.js";
import {ENDINGS} from "../dist/result-content.js";
import {calculate,DIMENSION_RANGES,ISSUE_RANGES} from "../dist/scoring.js";
const RUNS=Number(process.argv[2]||500000),keys=[...Object.keys(DIMENSIONS),...Object.keys(ISSUES),"displayRescue","rawRescue"],values=Object.fromEntries(keys.map(k=>[k,[]])),endingCounts=Object.fromEntries([0,...Object.keys(ENDINGS).map(Number)].map(k=>[k,0])),kLimiter={succession:0,court:0,military:0,tied:0},militaryBands={equal0:0,under25:0,under40:0,atLeast50:0,atLeast60:0},endingSums=Object.fromEntries(Object.keys(ENDINGS).map(k=>[k,Object.fromEntries(["displayRescue",...Object.keys(DIMENSIONS),...Object.keys(ISSUES)].map(x=>[x,0]))])),overlap={eligible10:0,eligible11:0,eligible12:0,"10&11":0,"10&12":0,"11&12":0,"10&11&12":0};
for(let n=0;n<RUNS;n++){const r=calculate(QUESTIONS.map(()=>Math.floor(Math.random()*4)));Object.keys(DIMENSIONS).forEach(k=>values[k].push(r.normalized[k]));Object.keys(ISSUES).forEach(k=>values[k].push(r.issues[k]));values.displayRescue.push(r.displayRescue);values.rawRescue.push(r.rawRescue);endingCounts[r.ending.number]++;const sums=endingSums[r.ending.number];sums.displayRescue+=r.displayRescue;Object.keys(DIMENSIONS).forEach(k=>sums[k]+=r.normalized[k]);Object.keys(ISSUES).forEach(k=>sums[k]+=r.issues[k]);const c=r.ending.checks,c10=!!c[10],c11=!!c[11],c12=!!c[12];if(c10)overlap.eligible10++;if(c11)overlap.eligible11++;if(c12)overlap.eligible12++;if(c10&&c11)overlap["10&11"]++;if(c10&&c12)overlap["10&12"]++;if(c11&&c12)overlap["11&12"]++;if(c10&&c11&&c12)overlap["10&11&12"]++;const trio=[["succession",r.issues.succession],["court",r.issues.court],["military",r.issues.military]],min=Math.min(...trio.map(x=>x[1])),lowest=trio.filter(x=>x[1]===min);if(lowest.length>1)kLimiter.tied++;else kLimiter[lowest[0][0]]++;const m=r.issues.military;if(m===0)militaryBands.equal0++;if(m<25)militaryBands.under25++;if(m<40)militaryBands.under40++;if(m>=50)militaryBands.atLeast50++;if(m>=60)militaryBands.atLeast60++;}
const pct=[.1,.25,.5,.75,.9,.95,.99],stats=a=>{a.sort((x,y)=>x-y);const mean=a.reduce((x,y)=>x+y,0)/a.length,out={min:+a[0].toFixed(2),max:+a.at(-1).toFixed(2),mean:+mean.toFixed(2)};pct.forEach(p=>out[`P${p*100}`]=+a[Math.floor((a.length-1)*p)].toFixed(2));return out;};
const percentages=o=>Object.fromEntries(Object.entries(o).map(([k,v])=>[k,{count:v,percent:+(v/RUNS*100).toFixed(3)}]));
const endingProfiles=Object.fromEntries(Object.keys(ENDINGS).map(k=>{const count=endingCounts[k],s=endingSums[k],avg=x=>count?+(s[x]/count).toFixed(2):null;return[`${k} ${ENDINGS[k].name}`,{count,percent:+(count/RUNS*100).toFixed(4),averageDisplayRescue:avg("displayRescue"),averageDimensions:Object.fromEntries(Object.keys(DIMENSIONS).map(x=>[x,avg(x)])),averageIssues:Object.fromEntries(Object.keys(ISSUES).map(x=>[x,avg(x)]))}]}));
const report={runs:RUNS,theoreticalRanges:{dimensions:DIMENSION_RANGES,issues:ISSUE_RANGES},distributions:Object.fromEntries(keys.map(k=>[k,stats(values[k])])),kAnalysis:{limiter:percentages(kLimiter),military:percentages(militaryBands)},highEndingOverlap:percentages(overlap),endingProfiles,unclassified:{count:endingCounts[0],percent:+(endingCounts[0]/RUNS*100).toFixed(4)}};
console.log(JSON.stringify(report,null,2));
